In [2]:
import numpy as np

In [29]:
a = np.diag([1,-1,1])
a
# diag + no ones

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  1]])

In [30]:
at = a.transpose()

In [31]:
at*a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
numpy.linalg.det(a)

-1.0

# Верхнетреугольная, ортогональная

In [58]:
m = np.triu([[1,1,],[1,1,],], 0)
m

array([[1, 1],
       [0, 1]])

In [59]:
m.transpose()

array([[1, 0],
       [1, 1]])

In [60]:
m * m.transpose()

array([[1, 0],
       [0, 1]])

# Нижнетреугольная, ортогональная

In [62]:
m = np.tril([[1,1,],[1,1,],], 0)
m

array([[1, 0],
       [1, 1]])

In [63]:
m.transpose()

array([[1, 1],
       [0, 1]])

In [64]:
m * m.transpose()

array([[1, 0],
       [0, 1]])

# Матрица, у которой определитель = 1, и все элементы не равны 0

In [78]:
a = np.array([[1,2],[1,3],])
a

array([[1, 2],
       [1, 3]])

In [79]:
np.linalg.det(a)

1.0

In [88]:
np.eye(2).dot(np.array([[1,1],[1,2]]))

array([[1., 1.],
       [1., 2.]])

In [89]:
np.eye(2).dot(np.array([[1,1],[1,2]])).dot(np.array([[1,1],[1,2]]))

array([[2., 3.],
       [3., 5.]])

In [104]:
np.array([[-1,1],[1,3]])

array([[-1,  1],
       [ 1,  3]])

# Собственные значения

In [121]:
a = np.array([[2, 2],[1, 3]])

In [122]:
w, v = np.linalg.eig(a)

In [123]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]
