In [11]:
import numpy as np

In [14]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
B = np.eye(3)
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
S = A + B

In [29]:
v = np.array([1,2,3])

In [30]:
sum_res = S.dot(v)

In [31]:
inv = np.linalg.inv(S)

In [32]:
inv

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])