In [37]:
import numpy as np

# Матрицы

In [63]:
A = np.array([[1,2,],[4,6]])
B = np.array([[1,1,],[2,2]])

In [66]:
A.shape

(2, 2)

In [67]:
B.shape

(2, 2)

In [68]:
A+B

array([[2, 3],
       [6, 8]])

# + -

# Умножение

In [71]:
B.dot(A)

array([[ 5,  8],
       [10, 16]])

# Обратная

In [75]:
A_inv = np.linalg.inv(A)

In [76]:
A @ A_inv

array([[1., 0.],
       [0., 1.]])